Extensible suffix behaviour (timestamp, count) through trait SuffixScheme (#7)
* "allow to add timestamp suffix to log path" PR by gfreezy

squashed and rebased by Erlend Langseth <3rlendhl@gmail.com>

* Extensible suffix behaviour (timestamp, count) through trait SuffixScheme

In the count case, changed from unintuitive O(1) renaming, to intuitive
O(N) cascade of renames.

* Make chrono dep optional

* Fix clippy warnings and errors

There were errors like
```
error: written amount is not handled. Use `Write::write_all` instead
   --> src/lib.rs:278:25
    |
278 |                         file.write(&buf[..bytes_left])?;
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[deny(clippy::unused_io_amount)]` on by default
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#unused_io_amount
```

Seems like a good catch by clippy.

* Add timestamp_age_rotation test, fix a bug

Bug:
 - have to use NaiveDateTime to parse timezone-less string, and not DateTime
 - suffix_to_string was wrong

- and adjust some tests

* Document how to use age as file limit

Co-authored-by: Alex.F <gfreezy@gmail.com>